micronaut:
  application:
    name: gerenciadorChavePixGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}

datasources:
  default:
    url: ${DATASOURCE_URL:`jdbc:postgresql://localhost:5433/gerenciador_chave_pix`}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    auto-commit: true
    maximum-pool-size: 50
    minimum-idle: 2
    idle-timeout: 600000
    data-source-properties:
      reWriteBatchInserts: true
      disableColumnSanitiser: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true


bcb:
  pix:
    url: ${BCB_URL:`http://localhost:8082`}

erp:
  itau:
    url: ${ERP_ITAU_URL:`http://localhost:9091`}